#!/usr/bin/env bash
# redirecting a “301 Moved Permanently”

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" >> /var/www/html/index.html
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo service nginx start
