#!/usr/bin/env bash
# redirecting a 301 Moved Permanently

sudo apt-get update
sudo apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo chmod -R 777 /etc/nginx
sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo service nginx restart
