#!/usr/bin/env bash
# That configure HAproxy with version equal or greater than 1.5

sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get update
sudo apt-get install -y haproxy
echo "frontend localnodes
	bind *:80
	mode http
	default_backend nodes

	backend nodes
	mode http
	balance roundrobin
	server 1159-web-01 35.229.75.124:80
	server 1159-web-02 54.173.156.111:80
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
