#!/usr/bin/env bash
# Nginx running as nginx user like I did for task 1
sudo chmod +rwx /etc/nginx/nginx.conf
sudo sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo pkill -f apache2
sudo -u nginx service nginx start

